name: Run Unit and Function Tests

on:
    push:
        branches: 
            - '*'
    pull_request:
        branches: [ master ]

jobs:
    run_styleCheck:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v7
        - uses: mamba-org/setup-micromamba@v3
          with:
            environment-file: environment.yml
            init-shell: bash
        - run: pycodestyle $(git ls-files "*.py")
          shell: bash -l {0}
    run_unit_test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v7
        - uses: mamba-org/setup-micromamba@v3
          with:
            environment-file: environment.yml
            init-shell: bash
        - run: |
            cd test
            python -m unittest test_my_utils
          shell: bash -l {0}
    run_function_test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v7
        - uses: mamba-org/setup-micromamba@v3
          with:
            environment-file: environment.yml
            init-shell: bash
        - run: |
            cd test
            bash test_print_fires.sh

